ci: add continuous delivery

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,5 +1,8 @@
 version: 2.1
 
+orbs:
+  slack: circleci/slack@3.4.2
+
 executors:
   node:
     docker:
@@ -17,7 +20,6 @@ jobs:
             echo "******** Node *****" && node -v
             echo "******** Npm **********" && npm -v
       - run: env
-
       # Download and cache npm dependencies
       - restore_cache:
           keys:
@@ -29,7 +31,6 @@ jobs:
           key: v1-npm-packages-{{ checksum "package-lock.json" }}
           paths:
             - node_modules
-
       # Build
       - run:
           name: Build
@@ -50,16 +51,52 @@ jobs:
           key: v1-npm-packages-{{ checksum "package-lock.json" }}
           paths:
             - node_modules
-
       # Run linter
       - run:
           name: Run linter
           command: make test@lint
 
-workflows:
-  version: 2.1
+  publish:
+    machine: true
+    steps:
+      - checkout
+      - run:
+          name: Check VERSION file
+          command: |
+            echo 'export CURRENT_VERSION=`git ls-remote --tags --refs --sort="v:refname" $CIRCLE_REPOSITORY_URL | tail -n1 | sed 's/.*\///'`
+            if [ "$(cat VERSION)" == "${CURRENT_VERSION}" ]; then
+              echo "Error: VERSION file must be updated"
+              exit 1
+            else
+              echo "Version $(cat VERSION) will be deployed"
+            fi
+      - run:
+          name: Tag GitHub version
+          command: |
+            git config --global user.email $GIT_USER_EMAIL
+            git config --global user.name $GIT_USER_NAME
+            git tag $(cat VERSION)
+            git push --tag origin
 
+workflows:
+  version: 2
   workflow:
     jobs:
       - build
       - linter
+      - slack/approval-notification:
+          context: cospirit
+          message: Production deployment is awaiting approval
+          requires: [ build, linter ]
+          filters:
+            branches:
+              only: master
+      - wait-for-approval:
+          type: approval
+          requires: [ build, linter ]
+          filters:
+            branches:
+              only: master
+      - publish:
+          context: cospirit
+          requires: [ wait-for-approval ]
